### ISSUE TITLE
Allow to derive a JSON keystore from a mnemonic

### ISSUE THREAD

**Issue by lcswillems** [multiversx/mx-sdk-py-cli#147]
It is possible to derive a PEM from a mnemonic. It would be great to be able to derive a JSON keystore from a mnemonic

**Comment by andreibancioiu** [comment]
Using [erdpy-eggs-wallet](https://github.com/ElrondNetwork/sdk-erdpy-eggs-wallet/blob/main/erdpy_wallet/user_test.py) (documentation not ready at this moment), it is possible as follows:

```
Mnemonic -> UserSecretKey -> UserWallet
```

**Comment by lcswillems** [comment]
Great!

**Comment by schimih** [comment]
Hey @lcswillems 

this can be closed because can be implemented with wallet convert from mxpy
https://github.com/multiversx/mx-sdk-py-cli/blob/main/CLI.md#walletconvert
