### ISSUE TITLE
erdpy lacks colored logging output

### ISSUE THREAD

**Issue by miohtama** [multiversx/mx-sdk-py-cli#16]
Currently erpy uses Python default stdout logging - which is not ideal for reading.

<img width="844" alt="image" src="https://user-images.githubusercontent.com/49922/130315407-0c5d0e80-e37e-4c5c-942c-37ae8072760c.png">

Most high quality command line applications now use colored output.

The situation can be easily improved with two or three lines of code by installing [coloredlogs](https://pypi.org/project/coloredlogs/) as a dependency.

**Comment by popenta** [comment]
Hello,

We have prepared this in the new mxpy release, `mxpy v8`. This is the [PR](https://github.com/multiversx/mx-sdk-py-cli/pull/297).
Instead of `coloredlogs` we are using the `RichHandler` from `rich.logging` since we already had it as a dependency.
