### ISSUE TITLE
Running local testnet involves too many manual steps

### ISSUE THREAD

**Issue by miohtama** [multiversx/mx-sdk-py-cli#19]
To get a local testnet running you need to do multiple manual steps (setting branches, creating config files):

https://docs.elrond.com/developers/setup-local-testnet/

Ideally, everything should be a single command line command. There is no reason why `erdpy` cannot come with sane defaults that allows running a local testnet with one command line command.

This would greatly improve the developer experience.

**Comment by MWFIAE** [comment]
Just wanted to mention:

Do you know the elrond ide extension for vs code?
It allows you to start a local testnet without much setup :)

**Comment by miohtama** [comment]
If there is a such way it should be highlighted in the documentation.

**Comment by bitconnector21** [comment]
A dockerized version would be nice.

**Comment by schimih** [comment]
hey @miohtama ,

Take a look here:
https://github.com/gfusee/xnetwork

I will close this issue given the utility of the xnetwork developed by @gfusee.
