### ISSUE TITLE
mxpy contract build improvement - use a smarter default for "cargo-target-directory"

### ISSUE THREAD

**Issue by andreibancioiu** [multiversx/mx-sdk-py-cli#273]
The default value of `cargo-target-directory` is unfortunate, and might lead to long build times - especially when working with and building more contracts (using a single default folder would have an impact on build caching).

**Comment by andreibancioiu** [comment]
Actually, in the near future, `mxpy contract build` will delegate all its functionality to `sc-meta`. This, in turn, would be responsible with setting an appropriate default value for `targetdir`.

**Comment by popenta** [comment]
This issue has been solved in this [PR](https://github.com/multiversx/mx-sdk-py-cli/pull/283)
