### ISSUE TITLE
mxpy-up: check all requirements

### ISSUE THREAD

**Issue by andreibancioiu** [multiversx/mx-sdk-py-cli#307]
E.g.:
 - build-essentials (probably only at "deps install rust")

Then, simplify docs, remove paragraphs not needed anymore (since the user is warned by mxpy-up to install it). E.g. `libncurses` is not actually needed anymore.

Requirements:
 - check implementation using GitHub Workflows (Ubuntu old and new, MacOS)

**Comment by popenta** [comment]
The dependency was removed from the GH workflow, and it works as expected. Will close this issue.
