### ISSUE TITLE
mxpy-up: make installer less verbose

### ISSUE THREAD

**Issue by andreibancioiu** [multiversx/mx-sdk-py-cli#308]
Currently, the output of mxpy-up is quite verbose, and the users tend to ignore the important notifications, as well.

We can make the installer less verbose. For example, we can adjust the implementation of `run_in_venv()` to only dump the `stdout` & `stderr` in case of errors.

Some references:
 - https://stackoverflow.com/a/17679894 (not actually recommended in our case)
 - `subprocess.check_call()`, `subprocess.check_call()`

**Comment by popenta** [comment]
Solved in this [PR](https://github.com/multiversx/mx-sdk-py-cli/pull/322)
