### ISSUE TITLE
mxpy-up: currently, some users confirm "Do you understand the above?" without reading the notifications

### ISSUE THREAD

**Issue by andreibancioiu** [multiversx/mx-sdk-py-cli#309]
Think about, and implement a mechanism that makes the users to pay more attention to the notifications displayed by the installer.

E.g.:
 - add more intrusive confirmation messages
 - consider adding some colors

**Comment by popenta** [comment]
We've made a PR to make the installation of `mxpy` less verbose. We've significantly reduced the number of lines making it much easier to read.
Check out the PR [here](https://github.com/multiversx/mx-sdk-py-cli/pull/322).
