### ISSUE TITLE
mxpy wallet convert: add support for exporting public keys and bech32 addresses

### ISSUE THREAD

**Issue by andreibancioiu** [multiversx/mx-sdk-py-cli#327]
Extend the set of `WALLET_FORMATS` to also include `WALLET_FORMAT_PUBLIC_KEY` and `WALLET_FORMAT_BECH32_ADDRESS`. 

**To be discussed whether we should have `wallet convert` or `wallet export`.**

E,g, export the bech32 address, given a wallet file:

```
mxpy wallet convert --infile alice.pem --in-format pem --out-format bech32-address
```

E.g. export the hex-encoded public key:

```
mxpy wallet convert --infile alice.pem --in-format pem --out-format public-key
```

**Comment by popenta** [comment]
Now we can convert a wallet to an address using `--out-format address-bech32` or `--out-format address-hex`.

E,g, export the bech32 address, given a wallet file:
```
mxpy wallet convert --infile alice.pem --in-format pem --out-format address-bech32
```

E.g. export the hex-encoded public key:
```
mxpy wallet convert --infile alice.pem --in-format pem --out-format address-hex
```

The PR can be found [here](https://github.com/multiversx/mx-sdk-py-cli/pull/328).
