### ISSUE TITLE
mxpy-up: check old / deprecated entries in mxpy.json and ask the user to remove them

### ISSUE THREAD

**Issue by andreibancioiu** [multiversx/mx-sdk-py-cli#337]
Original issue: https://discord.com/channels/1045353153073258557/1154410478253121599/1154416541106978838

**Comment by popenta** [comment]
This is done, will be live in **mxpy v9.2.0**. The active config is checked against the default config and a warning is displayed that asks the user to remove any deprecated entries in the active config.
