### ISSUE TITLE
erdpy code examples not helpful

### ISSUE THREAD

**Issue by miohtama** [multiversx/mx-sdk-py-cli#37]
The erdpy documentation refers to code examples on this page:

https://docs.elrond.com/sdk-and-tools/erdpy/writing-and-running-erdpy-scripts/

However this code examples are not helpful. For example here:

https://github.com/ElrondNetwork/elrond-sdk/tree/master/examples

Any of these examples contain zero code comments. For example, they do not example the purpose of the example and what it is supposed to achieve. Thus, this material is not high quality for learning purposes.

**Comment by tommyhutcheson** [comment]
Agree, I'd would love to see some examples of using the python SDK to create NFTs.

**Comment by schimih** [comment]
Hey @miohtama ,

in the meantime a cookbook has been added to the documentation:
https://docs.multiversx.com/sdk-and-tools/sdk-py/sdk-py-cookbook/

Please let us know if you think more examples should be added. Thanks!
