### ISSUE TITLE
Experiment with installation using "pipx". Consider removal of "mxpy-up"

### ISSUE THREAD

**Issue by andreibancioiu** [multiversx/mx-sdk-py-cli#370]

**Comment by popenta** [comment]
From the upcoming release, **mxpy** will be installable via **pipx** by running:
```sh
pipx install multiversx-sdk-cli
```

The PR can be found [here](https://github.com/multiversx/mx-sdk-py-cli/pull/374).

We'll keep `mxpy-up` for now, but maybe in the future it will be removed.
