### ISSUE TITLE
Do not automatically install Rust on "contract build"

### ISSUE THREAD

**Issue by andreibancioiu** [multiversx/mx-sdk-py-cli#371]
Should overcome issues such as:
 - https://t.me/MultiversXDevelopers/121311
 - https://t.me/MultiversXDevelopers/121314

Should also ameliorate https://github.com/multiversx/mx-sdk-py-cli/issues/338, since the underlying error of not being able to install `sc-meta` will not be hidden anymore by the error that happens at the time of running `contract build`: `No such file or directory: sc-meta`.

Additionally, do not perform Rust installation / installation check on `mxpy contract templates`. Currently, the output of `mxpy contract templates is`:

```
Found extra arguments in mxpy.json. Final arguments: ['contract', 'templates']
INFO     projects.templates: Checking if the necessarry dependencies are installed.                           templates.py:35
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ We recommend using rust nightly-2023-05-26. If you'd like to overwrite your current version please run `mxpy deps install │
│ rust --overwrite`.                                                                                                        │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
INFO     modules: install: key=rust, tag=nightly-2023-05-26, overwrite=False                                   modules.py:283
INFO     modules: which ...
INFO     myprocess: run_process: ['sc-meta', 'templates'], in folder: None                                    myprocess.py:12
INFO     myprocess: Successful run. Output:                                                                   myprocess.py:16
...
```

Instead, perhaps, do `ensure_rust()` or something similar, that only checks for rust, without installing it.

**Comment by popenta** [comment]
**mxpy** does not automatically install Rust on any contract operation.
Fixed in PR https://github.com/multiversx/mx-sdk-py-cli/pull/376.
