### ISSUE TITLE
Singleton config pattern not a good design pattern

### ISSUE THREAD

**Issue by miohtama** [multiversx/mx-sdk-py-cli#38]
Currently erdpy uses a singleton configuration pattern where it encourages the Python code to use `erdpy.config` module for any configuration passed along.

https://github.com/ElrondNetwork/elrond-sdk-erdpy/blob/main/erdpy/config.py

While this may work for simple scripts, this is problematic in many ways when building any non-trivial Python application code. 

Some examples may include:

* A web-server kind application uses fork-like scaling and needs to read configuration from the specific place and from the specific file at the specific time of the application life cycle

* A web-server application, like block explorer, could try to connect to multiple Elrond chain simultaneously with each having its own config

* Unit-test code may need several configurations, especially if it plans to run tests parallel

* There are an inversion of control issues

A better approach would be to encapsulate all configuration related functionality to its own class `Config` and then have the library user to explicitly to create the `Config` instance when using the library, to avoid any [inversion of control](https://en.wikipedia.org/wiki/Inversion_of_control) issues.

**Comment by popenta** [comment]
Since **mxpy** is not a package anymore, it's meant to be used only as a CLI tool. For builing dApps the libraries sdk-py-core, sdk-py-wallet and sdk-py-network-providers should be used instead.
