### ISSUE TITLE
Transaction.value should be an int

### ISSUE THREAD

**Issue by miohtama** [multiversx/mx-sdk-py-cli#40]
Currently `Transaction.value` is string. Unlike JavaScript, Python has been able to handle arbitrary sized integers for almost a decade now.  There is no reason to use strings for numbers in Python.

The following code fails unintuitively

```python
proxy = ElrondProxy("https://devnet-gateway.elrond.com")
sender = Account(pem_file="test-wallet.pem")
sender.sync_nonce(proxy)

tx = Transaction()
tx.nonce = sender.nonce
tx.value = int(0.05 * 10**18)  # 0.05 ERD, as required for issuing a token according to the documentation
tx.sender = sender.address.bech32()
# System contract address to issue out the new token as per
# https://docs.elrond.com/developers/esdt-tokens/#issuance-of-fungible-esdt-tokens
tx.receiver = "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u"
tx.gasPrice = 1000000000
tx.gasLimit = 50000
tx.data = ""
tx.chainID = "D"  # For devnet https://devnet-gateway.elrond.com/network/config

# "Should be autofilled with 1 I think:)
# tx.version = config.get_tx_version()

tx.signature = signing.sign_transaction(tx, sender)
tx.send(proxy)
```

Transaction object does not correctly serialise `value` to string, as expected for JSON payload. JSON itself can handle arbitrary precision numbers and are not limited to 64 bit floating points. The error comes from somewhere from the Go server code:

```
ProxyRequestError: Proxy request error for url [https://devnet-gateway.elrond.com/transaction/send]: {'data': None, 'error': 'validation error: json: cannot unmarshal number into Go struct field Transaction.value of type string', 'code': 'bad_request'}
```

**Comment by schimih** [comment]
Hey @miohtama 

This can be closed because the new sdk-py-core library has a new design on Transaction class:
https://github.com/multiversx/mx-sdk-py-core/blob/main/multiversx_sdk_core/transaction.py#L26

Thanks!
Please open the issue again if needed.
