### ISSUE TITLE
Adder template README insufficient

### ISSUE THREAD

**Issue by miohtama** [multiversx/mx-sdk-py-cli#41]
Currently the `adder` template, as recommended by Elrond documentation, generates the following README.

For any meaningful purpose of development, this README is too outlining and is not helpful for an outsider. It has too many gaps, does not give any context for the commands and so on.

```
# Interaction

## On devnet

Deploy & interact with contract:

python3 ./interaction/playground.py --pem=./testnet/wallets/users/alice.pem --proxy=http://localhost:7950

Interact with existing contract:

python3 ./interaction/playground.py --pem=./testnet/wallets/users/alice.pem --proxy=http://localhost:7950 --contract=erd1...

## On testnet

Deploy & interact with contract:

python3 ./interaction/playground.py --pem=my.pem --proxy=https://testnet-gateway.elrond.com

Interact with existing contract:

python3 ./interaction/playground.py --pem=my.pem --proxy=https://testnet-gateway.elrond.com --contract=erd1...
```

**Comment by schimih** [comment]
Hey @miohtama ,

You can have a look for more comprehensive documentation:
here: https://docs.multiversx.com/developers/tutorials/crowdfunding-p1
and here: https://docs.multiversx.com/sdk-and-tools/sdk-py/sdk-py-cookbook/

Let us know if other issues may seem relevant to you.
