### ISSUE TITLE
Allow 'erdpy contract new ProjectName' without specifying template 

### ISSUE THREAD

**Issue by keyur555** [multiversx/mx-sdk-py-cli#61]
Hi,

currently you have to choose a template when you want to create a new contract. It would be nice to also have the option to omit the template argument to start with a fresh project without example files.

Let me know what you think :)

**Comment by schimih** [comment]
Hey @keyur555 
The new template system/functionality will be a feature of the wasm-rs SDK.

Will close this issue. Thanks! :raised_hands:
