### ISSUE TITLE
Clarify the decimal position in Account.get balance

### ISSUE THREAD

**Issue by tredondo** [multiversx/mx-sdk-py-cli#73]
If I run `erdpy account.get --proxy ... --balance --address <ADDRESS>`, the result is impossible to read without additional context:

    10000000000000000

Is that 1 EGLD? 0.1? 0.00001? Am I a trillionaire?

I can't find any documentation about this in the CLI help or in [the docs](https://github.com/ElrondNetwork/elrond-sdk-erdpy/blob/main/erdpy/CLI.md#accountget). If I omit `--balance`, there's still no decimal position information.

**Comment by schimih** [comment]
Hey @tredondo 
you can always use: https://utils.multiversx.com/converters#amounts-formatting.
