### ISSUE TITLE
erdpy - LedgerError

### ISSUE THREAD

**Issue by RazvanCretu** [multiversx/mx-sdk-py-cli#82]
Hello

I was trying to interact with erdpy using a ledger nano s with it, but it keeps raising an error.

Here's the traceback:

* **CLI**:

> INFO:ledger:Ledger: please confirm the transaction on the device
> CRITICAL:cli:Ledger error: signature failed: invalid message

* **Py3.9.7 Script**:

---------------------------------------------------------------------------
LedgerError                               Traceback (most recent call last)
/tmp/ipykernel_6293/3001836644.py in <module>
     14 
     15 account = LedgerAccount(0,0)
---> 16 tx.sign(account)
     17 
     18 payload = tx.to_dictionary()

~/anaconda3/lib/python3.9/site-packages/erdpy/transactions.py in sign(self, account)
     59     def sign(self, account: Account):
     60         self.validate()
---> 61         self.signature = account.sign_transaction(self)
     62 
     63     def validate(self) -> None:

~/anaconda3/lib/python3.9/site-packages/erdpy/accounts.py in sign_transaction(self, transaction)
    102             transaction.set_options(TX_HASH_SIGN_OPTIONS)
    103 
--> 104         signature = do_sign_transaction_with_ledger(transaction.serialize(),
    105                                                     account_index=self.account_index,
    106                                                     address_index=self.address_index,

~/anaconda3/lib/python3.9/site-packages/erdpy/ledger/ledger_functions.py in do_sign_transaction_with_ledger(tx_payload, account_index, address_index, sign_using_hash)
     18 
     19     logger.info("Ledger: please confirm the transaction on the device")
---> 20     signature = ledger_handler.sign_transaction(tx_payload, sign_using_hash)
     21     ledger_handler.close()
     22 

~/anaconda3/lib/python3.9/site-packages/erdpy/ledger/ledger_app_handler.py in sign_transaction(self, marshaled_tx, should_use_hash_signing)
     96             offset += chunk_size
     97 
---> 98         return self.get_signature_from_apdus(apdus)
     99 
    100     def get_signature_from_apdus(self, apdus) -> str:

~/anaconda3/lib/python3.9/site-packages/erdpy/ledger/ledger_app_handler.py in get_signature_from_apdus(self, apdus)
    116             if err != '':
    117                 err_message += ': ' + err
--> 118             raise LedgerError(err_message)
    119 
    120         response_body = response[1:]

LedgerError: Ledger error: signature failed: invalid message

====

Any idea how I could fix this?

**Comment by Quentus123** [comment]
In your Ledger, open Elrond App then go to Settings > Contract data and set to yes

**Comment by schimih** [comment]
Hey @RazvanCretu ,
Due to the age of the pending feedback, I will close this issue. Please reopen it if the problem still persists.
