### ISSUE TITLE
Trying to create a new wallet or deriving an existing one give "bad key length"

### ISSUE THREAD

**Issue by jamiebullock** [multiversx/mx-sdk-py-cli#94]
On macOS 12.1, M1 Macbook Air...

```
erdpy -v      
erdpy 1.0.24
```

If I do either:

```
erdpy wallet new --pem
```

Or:

```
erdpy --verbose wallet derive ./walletKey.pem --mnemonic
```

I get the following error:

```
Traceback (most recent call last):
  File "/Users/jamie/elrondsdk/erdpy-venv/bin/erdpy", line 8, in <module>
    sys.exit(main())
  File "/Users/jamie/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli.py", line 32, in main
    _do_main()
  File "/Users/jamie/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli.py", line 58, in _do_main
    args.func(args)
  File "/Users/jamie/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/cli_wallet.py", line 93, in new_wallet
    secret_key, pubkey = wallet.derive_keys(mnemonic)
  File "/Users/jamie/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/wallet/core.py", line 26, in derive_keys
    bip39seed = mnemonic_to_bip39seed(mnemonic)
  File "/Users/jamie/elrondsdk/erdpy-venv/lib/python3.8/site-packages/erdpy/wallet/core.py", line 39, in mnemonic_to_bip39seed
    stretched = hashlib.pbkdf2_hmac("sha512", mnemonic, passphrase, BIP39_PBKDF2_ROUNDS)
ValueError: [digital envelope routines: CRYPTO_internal] bad key length
```

**Comment by jamiebullock** [comment]
OK, I've done a little investigation on this, and it seems that the password argument to `pbkdf2_hmac` is limited to 128 bytes.

My guess is this is a limitation imposed by the underlying openssl implementation.

**Comment by IonutSKL** [comment]
Hey, 

I have the same error on macOS 12.2.1, M1 Pro. 

Do you have a workaround or something?

**Comment by andreibancioiu** [comment]
@jamiebullock, @IonutSKL, thank you for reporting the issue :pray: 

Until we come with an investigation and a fix, do you think you can use this CLI to create wallets (or the web wallet, for that matter):

https://github.com/ElrondNetwork/erdwalletjs-cli

Further reference:
 - https://docs.elrond.com/developers/creating-wallets

**Comment by pislaru** [comment]
and still, how to derive the pem file from mnemonic? because with the erdwalletjs is not possible

**Comment by andreibancioiu** [comment]
> 

@pislaru, `erdpy` commands support `json` wallet files as well - see the parameters `--keyfile`, `--passfile` :pray:

**Comment by ccorcoveanu** [comment]
@jamiebullock Is this reproducible on M1 with `erdpy 1.1.0`?

**Comment by IonutSKL** [comment]
Hey @ccorcoveanu, 

I've tried again after erdpy update.. so, my version is now: 
```
erdpy --version
erdpy 1.2.1
```

but, same error: 
```
ib/python/site-packages/erdpy/wallet/core.py", line 39, in mnemonic_to_bip39seed
    stretched = hashlib.pbkdf2_hmac("sha512", mnemonic, passphrase, BIP39_PBKDF2_ROUNDS)
ValueError: [digital envelope routines: CRYPTO_internal] bad key length
```

**Comment by lleoooell** [comment]
hello there,

up on this ? same error...

**Comment by vietcuongmonad** [comment]
Same man, I was following this tutorial: 
https://docs.elrond.com/developers/tutorials/your-first-dapp/#create-an-owner-wallet
and encounter the same error when trying to derive the pem file from mnemonic.
Any fix yet guys?

**Comment by popenta** [comment]
Hello,

We are now at `mxpy v7.1.0` and as far as we've tested this, the issue does not persist anymore.
